# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)

1.23.5


In [3]:
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/ayman/anaconda3/envs/tensorflow/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/ayman/anaconda3/envs/tensorflow/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/ayman/anaconda3/envs/tensorflow/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/ayman/anaconda3/envs/tensorflow/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    foun

#### 3. Create a null vector of size 10

In [4]:
vec1 = np.zeros(10)
print(vec1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [5]:
# Memory size of vec1
print(vec1.nbytes)

80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
np.add?

Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            ~/anaconda3/envs/tensorflow/lib/python3.11/site-packages/numpy/__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
vec2 = np.zeros(10)
vec2[4] = 1
print(vec2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [8]:
vec3 = np.arange(10, 49)
vec3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last)

In [9]:
reversed_vec3 = vec3[::-1]
reversed_vec3

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
matrix_1 = np.arange(9).reshape(3,3)
matrix_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [11]:
array = [1, 2, 0, 0, 4, 0]
print(np.nonzero(array))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [12]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [13]:
random = np.random.rand(3,3,3)
random

array([[[0.18683231, 0.44092675, 0.12865734],
        [0.59431415, 0.89417214, 0.55040418],
        [0.53234086, 0.5138037 , 0.85724563]],

       [[0.03116512, 0.11332204, 0.30288606],
        [0.47350722, 0.40658645, 0.96902893],
        [0.19651667, 0.52041739, 0.39036482]],

       [[0.33882455, 0.22045334, 0.28722226],
        [0.94518703, 0.5519791 , 0.10374977],
        [0.04596478, 0.63702647, 0.87972035]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [14]:
random_10 = np.random.rand(10,10)
random_10

array([[0.56255848, 0.93087117, 0.78754552, 0.82850822, 0.48112428,
        0.98875406, 0.47855508, 0.44307369, 0.07209997, 0.01211088],
       [0.95574049, 0.90865558, 0.97181572, 0.29744543, 0.9557728 ,
        0.88330611, 0.94654587, 0.22174874, 0.61800887, 0.60857906],
       [0.56388336, 0.7791565 , 0.06643674, 0.27443214, 0.62146506,
        0.3608601 , 0.29487498, 0.77378789, 0.05337121, 0.35554008],
       [0.97959959, 0.28985232, 0.28416413, 0.53931953, 0.89704749,
        0.00238673, 0.35390014, 0.99132617, 0.25215249, 0.57992381],
       [0.07112102, 0.42837115, 0.43429814, 0.94349424, 0.52731313,
        0.7022345 , 0.71344237, 0.2825878 , 0.08424123, 0.73242385],
       [0.29268959, 0.07273529, 0.91435255, 0.51140745, 0.41432627,
        0.28805135, 0.65365143, 0.56299131, 0.95394265, 0.78674929],
       [0.07980178, 0.14046493, 0.94880092, 0.54492942, 0.9121809 ,
        0.84329661, 0.67343144, 0.39072759, 0.10314734, 0.02353443],
       [0.96342976, 0.04216423, 0.4891160

In [15]:
print(f"Minimum: {np.min(random_10)}\nMaximum: {np.max(random_10)}")

Minimum: 0.0023867291200097007
Maximum: 0.9913261662146569


#### 14. Create a random vector of size 30 and find the mean value

In [16]:
random = np.random.rand(30)
print(f"Mean: {np.mean(random)}")

Mean: 0.45663217928444294


#### 15. Create a 2d array with 1 on the border and 0 inside

In [17]:
matrix = np.zeros((5,5))
matrix[0:1,] = 1
matrix[-1,] = 1
matrix[:,0:1] = 1
matrix[:,-1] = 1
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [18]:
matrix = np.arange(1,17).reshape(4,4)
zero_matrix = np.zeros((6,6))
zero_matrix[1:-1, 1:-1] = matrix
print(zero_matrix)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  0.]
 [ 0.  5.  6.  7.  8.  0.]
 [ 0.  9. 10. 11. 12.  0.]
 [ 0. 13. 14. 15. 16.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [20]:
matrix = np.zeros((5,5))

val = 1
for i in range(4):
    matrix[i+1][i] = val
    val += 1
    
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [21]:
chess_board = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if(i+j)%2==0:
            chess_board[i][j] = 1
                 
print(chess_board)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
array = np.random.rand(6,7,8)
shape = (6,7,8)
index = 100

z = index % shape[2]
index //= z

y = index % shape[1]
index //= y

x = index % shape[0]

print(f"(x,y,z): ({x},{y},{z})")
print(f"Element: {array[0][4][4]}")

(x,y,z): (0,4,4)
Element: 0.5756710322876152
